import { MenuBar } from '../../../pages/MenuBar'
import { SwapPage } from '../../../pages/SwapPage'
import { NetworkSwitcher } from '../../../pages/NetworkSwitcher'

describe('Switching from maintet tests', () => {
  beforeEach(() => {
    SwapPage.visitSwapPage()
    MenuBar.connectWallet()
  })
  afterEach(() => {
    cy.disconnectMetamaskWalletFromAllDapps()
  })
  after(() => {
    cy.disconnectMetamaskWalletFromAllDapps()
    cy.wait(200)
  })
  it('Should switch from mainet to a. rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('ethereum')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arinkeby().click()
    cy.allowMetamaskToAddAndSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum Rinkeby')
  })
  it('Should switch from mainet to gnosis by dapp', () => {
    cy.changeMetamaskNetwork('ethereum')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.gnosis().click()
    cy.allowMetamaskToAddAndSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Gnosis')
  })
  it('Should switch from mainet to arbitrum by dapp', () => {
    cy.changeMetamaskNetwork('ethereum')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arbitrum().click()
    cy.allowMetamaskToAddAndSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum One')
  })
  it('Should switch from mainet to rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('ethereum')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.rinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Rinkeby')
  })
  it('Should switch from gnosis to mainet by dapp', () => {
    cy.changeMetamaskNetwork('Gnosis')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.ethereum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Ethereum')
  })
  it('Should switch from gnosis to arbitrum by dapp', () => {
    cy.changeMetamaskNetwork('Gnosis')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arbitrum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum One')
  })
  it('Should switch from gnosis to rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('Gnosis')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.rinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Rinkeby')
  })
  it('Should switch from rinkeby to mainet by dapp', () => {
    cy.changeMetamaskNetwork('rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.ethereum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Ethereum')
  })
  it('Should switch from rinkeby to arbitrum by dapp', () => {
    cy.changeMetamaskNetwork('rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arbitrum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum One')
  })
  it('Should switch from rinkeby to gnosis by dapp', () => {
    cy.changeMetamaskNetwork('rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.gnosis().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Gnosis Chain')
  })
  it('Should switch from rinkeby to a. rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum Rinkeby')
  })
  it('Should switch from a. rinkeby to mainet by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.ethereum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Ethereum')
  })
  it('Should switch from a. rinkeby to arbitrum by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arbitrum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum One')
  })
  it('Should switch from a. rinkeby to gnosis by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.gnosis().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Gnosis Chain')
  })
  it('Should switch from a. rinkeby to rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.rinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Rinkeby')
  })
  it('Should switch from arbitrum one to gnosis by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum one')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.gnosis().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Gnosis Chain')
  })

  it('Should switch from arbitrum one to mainet by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum one')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.ethereum().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Ethereum')
  })
  it('Should switch from arbitrum one to rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum one')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.arinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Arbitrum Rinkeby')
  })
  it('Should switch from arbitrum one to rinkeby by dapp', () => {
    cy.changeMetamaskNetwork('arbitrum one')
    MenuBar.getNetworkSwitcher().click()
    NetworkSwitcher.rinkeby().click()
    cy.allowMetamaskToSwitchNetwork()
    MenuBar.getNetworkSwitcher().should('contain.text', 'Rinkeby')
  })
})
