import { MenuBar } from '../../../../pages/MenuBar'
import { TokenMenu } from '../../../../pages/TokenMenu'
import { BridgePage } from '../../../../pages/BridgePage'
import { NetworkSwitcher } from '../../../../pages/NetworkSwitcher'
import { AddressesEnum } from '../../../../utils/enums/AddressesEnum'
import { ScannerFacade, SCANNERS } from '../../../../utils/facades/ScannerFacade'

describe('Bridge tests', () => {
  let balanceBefore: number
  const TRANSACTION_VALUE = 1

  before(() => {
    ScannerFacade.erc20TokenBalance(
      AddressesEnum.USDC_TOKEN_ARINKEBY,
      AddressesEnum.WALLET_PUBLIC,
      SCANNERS.ARBISCAN
    ).then((res: { body: { result: string } }) => {
      balanceBefore = parseFloat(res.body.result)
      console.log('ERC20 BALANCE BEFORE: ', balanceBefore)
      console.log('ERC20 BALANCE BEFORE: ', res)
    })
    BridgePage.visitBridgePage()
    MenuBar.connectWallet()
  })
  after(() => {
    cy.disconnectMetamaskWalletFromAllDapps()
    cy.resetMetamaskAccount()
    cy.wait(500)
  })
  it('Should initiate a bridging ', function () {
    if (isNaN(balanceBefore)) {
      this.skip() // Skipping test if Arbiscan is down
    }
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Enter amount')
    BridgePage.getTransactionValueInput().type(String(TRANSACTION_VALUE))
    BridgePage.getSelectTokenButton().click({ scrollBehavior: false })
    TokenMenu.chooseToken('usdc')
    BridgePage.getBridgeButton().should('contain.text', 'Select bridge below')
    BridgePage.getBridgeSelector('arbitrum').should('be.visible')
    BridgePage.getBridgedAmount().should('contain.text', String(TRANSACTION_VALUE))
    BridgePage.getBridgeSelector('arbitrum').click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Bridge to').click({ scrollBehavior: false })
    BridgePage.confirmBridging()
    cy.wait(5000) //METAMASK MODAL IS OPENING WITH 5 SEC DELAY WHICH IS TOO LONG FOR SYNPRESS
    cy.confirmMetamaskTransaction({})
    BridgePage.getBridgingInitiatedModal().should('contain.text', 'Bridging Initiated')
    BridgePage.closeBridgeInitiatedModal()
    BridgePage.getStatusTag(600000).should('contain.text', 'Pending')
    BridgePage.getBridgedFromChain().should('contain.text', 'Rinkeby')
    BridgePage.getBridgedToChain().should('contain.text', 'A. Rinkeby')
    BridgePage.getBridgedAssetName().should('contain.text', '1 USDC')
  })
  it('Should display transaction rejected when rejecting bridging in wallet ', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Enter amount')
    BridgePage.getTransactionValueInput().type(String(TRANSACTION_VALUE))
    BridgePage.getSelectTokenButton().click({ scrollBehavior: false })
    TokenMenu.chooseToken('usdc')
    BridgePage.getBridgeButton().should('contain.text', 'Select bridge below')
    BridgePage.getBridgeSelector('arbitrum').should('be.visible')
    BridgePage.getBridgedAmount().should('contain.text', String(TRANSACTION_VALUE))
    BridgePage.getBridgeSelector('arbitrum').click({ scrollBehavior: false })
    BridgePage.getBridgeButton().click({ scrollBehavior: false })
    BridgePage.confirmBridging()
    cy.wait(5000) //METAMASK MODAL IS OPENING WITH 5 SEC DELAY WHICH IS TOO LONG FOR SYNPRESS
    cy.rejectMetamaskTransaction()
    BridgePage.getTransactionErrorModal().should('be.visible').should('contain.text', 'Transaction rejected')
    BridgePage.closeTransactionErrorModal()
    BridgePage.getNetworkFromSelector().should('be.visible')
    BridgePage.getNetworkToSelector().should('be.visible')
  })
  it('Should select ethereum and select others networks as to', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.ethereum().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Connect to Ethereum').click({ scrollBehavior: false })
    cy.allowMetamaskToSwitchNetwork()
    NetworkSwitcher.getNetworkSwitcher().should('contain.text', 'Ethereum')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arbitrum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Arbitrum one')

    BridgePage.getSelectTokenButton().click({ scrollBehavior: false })
    TokenMenu.chooseToken('eth')
    BridgePage.getTokenSymbol().should('contain.text', 'ETH')

    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.gnosis().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Gnosis Chain')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Rinkeby')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should select Arbitrum and select others networks as to', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arbitrum().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Connect to Arbitrum').click({ scrollBehavior: false })
    cy.allowMetamaskToAddAndSwitchNetwork()
    NetworkSwitcher.getNetworkSwitcher().should('contain.text', 'Arbitrum One')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.ethereum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Ethereum')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.gnosis().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Gnosis Chain')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Rinkeby')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should select Gnosis Chain and select others networks as to', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.gnosis().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Connect to Gnosis Chain').click({ scrollBehavior: false })
    cy.allowMetamaskToAddAndSwitchNetwork()
    NetworkSwitcher.getNetworkSwitcher().should('contain.text', 'Gnosis Chain')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.ethereum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Ethereum')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arbitrum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Arbitrum one')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Rinkeby')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should select Rinkeby and select others networks as to', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Connect to Rinkeby').click({ scrollBehavior: false })
    cy.allowMetamaskToSwitchNetwork()
    NetworkSwitcher.getNetworkSwitcher().should('contain.text', 'Rinkeby')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.ethereum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Ethereum')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arbitrum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Arbitrum one')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.gnosis().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Gnosis Chain')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should select A. Rinkeby and select others networks as to', () => {
    BridgePage.getNetworkFromSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arinkeby().click({ scrollBehavior: false })
    BridgePage.getBridgeButton().should('contain.text', 'Connect to A. Rinkeby').click({ scrollBehavior: false })
    cy.allowMetamaskToAddAndSwitchNetwork()
    NetworkSwitcher.getNetworkSwitcher().should('contain.text', 'Arbitrum Rinkeby')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.ethereum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Ethereum')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.arbitrum().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Arbitrum one')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.gnosis().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Gnosis Chain')
    BridgePage.getNetworkToSelector().click({ scrollBehavior: false })
    NetworkSwitcher.rinkeby().click({ scrollBehavior: false })
    BridgePage.getNetworkToSelector().should('contain.text', 'Rinkeby')
  })
  it('Should switch from network based on wallet network', () => {
    cy.changeMetamaskNetwork('ethereum')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Ethereum')
    cy.changeMetamaskNetwork('arbitrum one')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Arbitrum one')
    cy.changeMetamaskNetwork('gnosis chain')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Gnosis Chain')
    cy.changeMetamaskNetwork('rinkeby')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Rinkeby')
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    BridgePage.getNetworkFromSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should display no tokens', () => {
    cy.changeMetamaskNetwork('ethereum')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Ethereum')
    cy.changeMetamaskNetwork('arbitrum one')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Arbitrum one')
    cy.changeMetamaskNetwork('gnosis chain')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Gnosis Chain')
    cy.changeMetamaskNetwork('rinkeby')
    BridgePage.getNetworkFromSelector().should('contain.text', 'Rinkeby')
    cy.changeMetamaskNetwork('arbitrum rinkeby')
    BridgePage.getNetworkFromSelector().should('contain.text', 'A. Rinkeby')
  })
  it('Should display history of bridge', function () {
    if (isNaN(balanceBefore)) {
      this.skip()
    }
    cy.changeMetamaskNetwork('rinkeby')
    BridgePage.getStatusTag(600000).should('contain.text', 'Confirmed')
    BridgePage.getBridgedFromChain().should('contain.text', 'Rinkeby')
    BridgePage.getBridgedToChain().should('contain.text', 'A. Rinkeby')
    BridgePage.getBridgedAssetName().should('contain.text', '1 USDC')

    ScannerFacade.erc20TokenBalance(
      AddressesEnum.USDC_TOKEN_ARINKEBY,
      AddressesEnum.WALLET_PUBLIC,
      SCANNERS.ARBISCAN
    ).should((res: { body: { result: string } }) => {
      expect(parseInt(res.body.result)).to.be.at.least(Number(balanceBefore) + Number(1000000))
    })
  })
})
