query getPairTokenPrices($pairAddress: ID, $timestamp: BigInt, $timeframe: PairTokenPriceTimeframe) {
  pairTokenPrices(
    first: 1000
    where: { pair_: { id: $pairAddress }, blockTimestamp_gt: $timestamp, timeframe: $timeframe }
    orderBy: blockNumber
    orderDirection: asc
  ) {
    id
    pair {
      token1 {
        symbol
      }
      token0 {
        symbol
      }
    }
    token0Address
    token1Address
    token0Price
    token1Price
    blockNumber
    blockTimestamp
    timeframe
  }
}
