query getSingleSidedStakingCampaign($campaignId: ID!) {
  singleSidedStakingCampaign(id: $campaignId) {
    ...SingleSidedStakingCampaignFragment
    stakeToken {
      ...StakeTokenFragment
    }
    rewards {
      ...SingleSidedStakingCampaignRewardFragment
    }
  }
}
