query LiquidityMiningCampaign($liquidityMiningCampaignId: ID!) {
  liquidityMiningCampaign(id: $liquidityMiningCampaignId) {
    address: id
    duration
    startsAt
    endsAt
    locked
    stakingCap
    rewards {
      token {
        address: id
        name
        symbol
        decimals
        derivedNativeCurrency
      }
      amount
    }
    stakedAmount
  }
}
