query LiquidityMiningCampaign($liquidityMiningCampaignId: ID!) {
  liquidityMiningCampaign(id: $liquidityMiningCampaignId) {
    ...LiquidityMiningCampaignFragment
    rewards {
      ...LiquidityMiningCampaignRewardFragment
    }
  }
}
