query Pair($pairId: ID!) {
  pair(id: $pairId) {
    id
    reserve0
    reserve1
    reserveNativeCurrency
    token0 {
      derivedNativeCurrency
    }
    token1 {
      derivedNativeCurrency
    }
    totalSupply
  }
}
