query UserLiquidityPositions($userId: String, $endsAtLowerLimit: BigInt!) {
  liquidityPositions(where: { user: $userId, liquidityTokenBalance_gt: 0 }) {
    pair {
      address: id
      reserve0
      reserve1
      reserveNativeCurrency
      reserveUSD
      totalSupply
      token0 {
        address: id
        name
        symbol
        decimals
      }
      token1 {
        address: id
        name
        symbol
        decimals
      }
      liquidityMiningCampaigns(where: { endsAt_gt: $endsAtLowerLimit }) {
        address: id
        duration
        startsAt
        endsAt
        locked
        stakingCap
        rewards {
          token {
            address: id
            name
            symbol
            decimals
            derivedNativeCurrency
          }
          amount
        }
        stakedAmount
        liquidityMiningPositions(where: { stakedAmount_gt: 0, user: $userId }) {
          id
        }
      }
    }
  }
  liquidityMiningPositions(where: { user: $userId, stakedAmount_gt: 0 }) {
    pair: targetedPair {
      address: id
      reserve0
      reserve1
      reserveNativeCurrency
      reserveUSD
      totalSupply
      token0 {
        address: id
        name
        symbol
        decimals
      }
      token1 {
        address: id
        name
        symbol
        decimals
      }
      liquidityMiningCampaigns(where: { endsAt_gt: $endsAtLowerLimit }) {
        address: id
        duration
        startsAt
        endsAt
        locked
        stakingCap
        rewards {
          token {
            address: id
            name
            symbol
            decimals
            derivedNativeCurrency
          }
          amount
        }
        stakedAmount
        liquidityMiningPositions(where: { stakedAmount_gt: 0, user: $userId }) {
          id
        }
      }
    }
  }
}
